// This file is auto-generated by @hey-api/openapi-ts

export type AuthMessage = {
    message: string;
};

export type Body_auth_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_documents_create_document = {
    file: string;
};

export type DocumentPublic = {
    file_url: string;
    id: string;
    filename?: (string | null);
    uploaded_at: string;
    extraction_status: ExtractionStatus;
};

export type DocumentsPublic = {
    data: Array<DocumentPublic>;
    count: number;
};

export type DocumentUpdate = {
    filename?: (string | null);
};

export type ExtractionStatus = 'pending' | 'success' | 'failed';

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_active?: boolean;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    full_name?: (string | null);
    is_active?: boolean;
    is_admin?: boolean;
    password: string;
};

export type UserPublic = {
    email: string;
    full_name?: (string | null);
    is_active?: boolean;
    is_admin?: boolean;
    id: string;
    created_at: string;
};

export type UserRegister = {
    full_name?: (string | null);
    email: string;
    password: string;
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    full_name?: (string | null);
    password?: (string | null);
    is_admin?: (boolean | null);
    is_active?: (boolean | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type AuthLoginAccessTokenData = {
    formData: Body_auth_login_access_token;
};

export type AuthLoginAccessTokenResponse = (Token);

export type AuthTestTokenResponse = (UserPublic);

export type AuthRecoverPasswordData = {
    email: string;
};

export type AuthRecoverPasswordResponse = (AuthMessage);

export type AuthResetPasswordData = {
    requestBody: NewPassword;
};

export type AuthResetPasswordResponse = (AuthMessage);

export type AuthRecoverPasswordHtmlData = {
    email: string;
};

export type AuthRecoverPasswordHtmlResponse = (unknown);

export type DocumentsCreateDocumentData = {
    formData: Body_documents_create_document;
};

export type DocumentsCreateDocumentResponse = (DocumentPublic);

export type DocumentsReadDocumentsData = {
    descending?: boolean;
    limit?: number;
    orderBy?: (string | null);
    search?: (string | null);
    skip?: number;
};

export type DocumentsReadDocumentsResponse = (DocumentsPublic);

export type DocumentsDeleteFileData = {
    id: string;
};

export type DocumentsDeleteFileResponse = (void);

export type DocumentsChangeFilenameData = {
    id: string;
    requestBody: DocumentUpdate;
};

export type DocumentsChangeFilenameResponse = (DocumentPublic);

export type DocumentsReadDocData = {
    id: string;
};

export type DocumentsReadDocResponse = (DocumentPublic);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UploadsReadDocumentData = {
    fileId: string;
};

export type UploadsReadDocumentResponse = (unknown);

export type UserCreateUserData = {
    requestBody: UserCreate;
};

export type UserCreateUserResponse = (UserPublic);

export type UserReadUsersData = {
    descending?: boolean;
    limit?: number;
    orderBy?: (string | null);
    search?: (string | null);
    skip?: number;
};

export type UserReadUsersResponse = (UsersPublic);

export type UserRegisterNewUserData = {
    requestBody: UserRegister;
};

export type UserRegisterNewUserResponse = (UserPublic);

export type UserReadMeResponse = (UserPublic);

export type UserDeleteUserMeResponse = (AuthMessage);

export type UserUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UserUpdateUserMeResponse = (UserPublic);

export type UserReadUserByIdData = {
    userId: string;
};

export type UserReadUserByIdResponse = (UserPublic);

export type UserUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UserUpdateUserResponse = (UserPublic);

export type UserDeleteUserData = {
    userId: string;
};

export type UserDeleteUserResponse = (AuthMessage);

export type UserUpdatePasswordData = {
    requestBody: UpdatePassword;
};

export type UserUpdatePasswordResponse = (AuthMessage);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (AuthMessage);

export type UtilsHealthCheckResponse = (boolean);