"""changed the maximum length of character

Revision ID: 4d4d20a89db7
Revises: 1835af861adc
Create Date: 2026-08-05 09:42:25.008634

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d4d20a89db7'
down_revision: Union[str, None] = '1835af861adc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'filename')
    # ### end Alembic commands ###
